url: ""
baseurl: ""
repository: "https://github.com/francescobianco/jekyll-html-pages"
title: "ðŸŒ Jekyll HTML Pages"
author: "B.Laude"

plugins: [jekyll-paginate, jekyll-sitemap, jekyll-feed, jekyll-seo-tag]

paginate: 5

navigation:
  - title: Home
    url: /

  - title: About
    url: /about.html

  - title: Contact
    url: /contact.html

  - title: Write new post
    url: /new.html
    target: _blank

custom_head: >
  <link rel='icon' href='/favicon.ico'>  
